AWSTemplateFormatVersion: "2010-09-09" 
Description: " creating a Vpc, IGW ,Public and Priavte Subs with routetable"

Resources:
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name 
          Value: cloud-vpc 

  MYIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: Name 
          Value: cloud-Igw

  IgwAttachment: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MYIGW
      VpcId: !Ref MyVpc  

  PublicSubnet: 
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref MyVpc
      Tags:
        - Key: Name 
          Value: MyPublic-Sub 

  PrivateSubnet: 
    Type: AWS::EC2::Subnet 
    Properties: 
      CidrBlock: 10.0.1.0/24 
      VpcId: !Ref MyVpc 
      Tags:
        - Key: Name 
          Value: MyPrivate-Sub 

  PublicRouteTable: 
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: Name 
          Value: publicroute
      VpcId: !Ref MyVpc 

  PublicRoute: 
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PublicRouteTable 
      GatewayId: !Ref MYIGW 

  PublicSubAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet

  PrivateRoutTable: 
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: Name 
          Value: Private-Rouetable
      VpcId: !Ref MyVpc  
  
  PrivateSubAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRoutTable
      SubnetId: !Ref PrivateSubnet

   


  
    

  